version: '3'
services:
    jenkins:
        image: jenkins/jenkins
        container_name: jenkins
        user: jenkins
        volumes:
            - /data/jenkins:/home/agu/docker/jenkins/data
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            JENKINS_HOST_HOME: "/data/jenkins"
        ports:
            - "8081:8080"
            - "5000:5000"
            - "50000:50000"
