version: "3"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        restart: always
        networks:
            - redis-net
networks:
    redis-net:
volumes:
    redis-data:
